version: '3'

services:
  node-app:
    env_file:
       - .env
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      POSTGRES_CONNECTION_STRING: postgresql://blizztrack:password@postgres
    depends_on:
      - postgres

  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: blizztrack
    restart: unless-stopped